travis:
  secure:
    BINSTAR_TOKEN: l/TKk7D5tiCcezZ1/A7aY0pPI+Y9y7ZaNLYF55Br65ZnhVQ2HRvdGhPn+WIptGG9sS40DoKLtbgRuJ/YJlczZPByYyXaW+qSXcq5FD8inztY/qNJV7pfwVZ3lVPOVT4bKAieXPvxYTqfzb0vLfuaGIfi9gC/xHZpY6yudbff6N1dZsFm7Y4ik+5S7sKScBjCavknWTSOl3TJLrUgguv9AHn3TpRE2vR0yG0sCPAl8GdPL9CjiG5uNxr1jY/hEodGFrOhNhu/GMKhheGNWTPfI5jE/cTh8ijk7xs2uVh6qcSCHMRzhV3aLriz8JdWGmY/dJBY3Yg79zAQBw/tOcsHM0WMTpuhZCICVpeq711+HpTZUpNrQljt/ECja4YVbbENR/X7UUk5t98+NIp61F1kZ9nVxY5FAgzjzwQm74iH/zQd2se6Pzk0MAKUyTFDHAE8ABl6FSkVCYNkvk2Vm5eMIFpHkkIg46OeLsqiRlC90HGxRlL+X+h+eSA5nFTbolVW3jNoGCzlqHgDo0E1blcgqVu8YuRu7VCsSPdcO/GCpl3wsGHVAhx2Sb63919NlnYQ6qW1EnmaTIVfFIy4TryHQPeHBrA2zBudWMXwX4Y+s2OUY4JfRYWsZxbGIW+F4KzQLGBeNZiBMWuTQQT0wgW0VTGw5GXbmqIgoIf0ClRpohs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
